export interface Template {
  name: string;
  description: string;
  blocks: string[];
}

export const BUILTIN_TEMPLATES: Template[] = [
  {
    name: "Meeting Notes",
    description: "Structured meeting agenda with sections",
    blocks: [
      "## Attendees",
      "",
      "## Agenda",
      "",
      "## Discussion",
      "",
      "## Action Items",
      "TODO ",
      "TODO ",
      "",
      "## Follow-up",
    ],
  },
  {
    name: "Project Brief",
    description: "Project overview with goals and milestones",
    blocks: [
      "## Overview",
      "",
      "## Goals",
      "TODO ",
      "TODO ",
      "",
      "## Milestones",
      "",
      "## Resources",
      "",
      "## Risks",
    ],
  },
  {
    name: "Weekly Review",
    description: "Reflect on the past week and plan ahead",
    blocks: [
      "## Wins this week",
      "",
      "",
      "## Challenges",
      "",
      "",
      "## Lessons learned",
      "",
      "## Next week priorities",
      "TODO ",
      "TODO ",
      "TODO ",
    ],
  },
  {
    name: "Bug Report",
    description: "Structured bug report template",
    blocks: [
      "## Summary",
      "",
      "## Steps to Reproduce",
      "1. ",
      "2. ",
      "3. ",
      "",
      "## Expected Behavior",
      "",
      "## Actual Behavior",
      "",
      "## Environment",
      "",
    ],
  },
  {
    name: "Daily Standup",
    description: "Quick daily update format",
    blocks: [
      "## Yesterday",
      "DONE ",
      "",
      "## Today",
      "TODO ",
      "",
      "## Blockers",
      "",
    ],
  },
  {
    name: "Decision Log",
    description: "Record important decisions and reasoning",
    blocks: [
      "## Decision",
      "",
      "## Context",
      "",
      "## Options Considered",
      "",
      "",
      "## Chosen Option",
      "",
      "## Rationale",
      "",
    ],
  },
];
