/**
 * Mock backend for testing MiNotes in a regular browser (outside Tauri).
 *
 * Provides an in-memory store with realistic test data.
 * Activates automatically when Tauri's invoke() is not available.
 */

import type {
  Page, Block, PageTree, Link, GraphStats, Property,
  FolderTreeRoot, QueryResult, GraphData,
} from "./api";

// ── In-memory store ──

const now = new Date().toISOString();
const today = new Date().toISOString().slice(0, 10);

let nextId = 100;
function genId(): string {
  return `mock-${++nextId}-${Date.now().toString(36)}`;
}

interface MockFolder {
  id: string;
  name: string;
  parent_id?: string;
  icon?: string;
  color?: string;
  position: number;
  collapsed: boolean;
  created_at: string;
  updated_at: string;
}

const pages: Map<string, Page> = new Map();
const blocks: Map<string, Block> = new Map();
const properties: Map<string, Property[]> = new Map();
const pendingJournals: Map<string, Page> = new Map();
const folders: Map<string, MockFolder> = new Map();
const favorites: Map<string, number> = new Map(); // pageId -> position
const trash: Set<string> = new Set(); // trashed page IDs
const trashedFolders: Set<string> = new Set();
const archived: Set<string> = new Set(); // archived page IDs
const archivedFolders: Set<string> = new Set();

// ── Seed test data ──

function seedData() {
  // Journal page
  const journalId = genId();
  pages.set(journalId, {
    id: journalId,
    title: `Journal/${today}`,
    position: 1,
    is_journal: true,
    journal_date: today,
    created_at: now,
    updated_at: now,
  });

  const jb1 = genId();
  blocks.set(jb1, {
    id: jb1, page_id: journalId, position: 1,
    content: "Welcome to today's journal. Start typing here.",
    format: "markdown", collapsed: false, created_at: now, updated_at: now,
  });

  // Getting Started page
  const gsId = genId();
  pages.set(gsId, {
    id: gsId, title: "Getting Started", position: 2,
    is_journal: false, created_at: now, updated_at: now,
  });

  const tutorialBlocks = [
    "This is a block. Press **Enter** to create a new one below.",
    "Type **[[** to link to another page. Try [[Project Alpha]]",
    "Press **/** for slash commands — headings, lists, code blocks.",
    "Press **Ctrl+Enter** to cycle: TODO → DOING → DONE",
    "Use **Ctrl+K** to search, or type **>** for commands.",
    "Press **Ctrl+J** to jump to today's journal.",
    "Press **Ctrl+,** for Settings. You're ready to go!",
  ];

  tutorialBlocks.forEach((content, i) => {
    const bid = genId();
    blocks.set(bid, {
      id: bid, page_id: gsId, position: i + 1,
      content, format: "markdown", collapsed: false,
      created_at: now, updated_at: now,
    });
  });

  // Project Alpha page
  const paId = genId();
  pages.set(paId, {
    id: paId, title: "Project Alpha", position: 3,
    is_journal: false, created_at: now, updated_at: now,
  });

  const projectBlocks = [
    "# Project Alpha",
    "This is a sample project page with nested blocks.",
    "## Tasks",
    "TODO Review the PRD document",
    "DOING Build the frontend components",
    "DONE Set up the development environment",
    "## Notes",
    "The architecture uses Rust + TypeScript with Tauri 2.",
    "Key insight: blocks are the fundamental unit of content.",
  ];

  let parentId: string | undefined;
  projectBlocks.forEach((content, i) => {
    const bid = genId();
    // Nest "TODO/DOING/DONE" blocks under "Tasks"
    const isTask = content.startsWith("TODO") || content.startsWith("DOING") || content.startsWith("DONE");
    const isNote = i >= 7;
    blocks.set(bid, {
      id: bid, page_id: paId, position: i + 1,
      parent_id: isTask ? parentId : isNote && i > 7 ? parentId : undefined,
      content, format: "markdown", collapsed: false,
      created_at: now, updated_at: now,
    });
    if (content === "## Tasks" || content === "## Notes") parentId = bid;
  });

  // Research Notes page
  const rnId = genId();
  pages.set(rnId, {
    id: rnId, title: "Research Notes", position: 4,
    is_journal: false, created_at: now, updated_at: now,
  });

  ["Exploring local-first architectures for note-taking apps.",
   "Key reference: [[Project Alpha]] for implementation details.",
   "CRDT sync is the future of collaborative editing.",
   "- [ ] Read the Automerge paper",
   "- [x] Review Logseq's outliner model",
  ].forEach((content, i) => {
    const bid = genId();
    blocks.set(bid, {
      id: bid, page_id: rnId, position: i + 1,
      content, format: "markdown", collapsed: false,
      created_at: now, updated_at: now,
    });
  });
  // Test Results page
  const trId = genId();
  pages.set(trId, {
    id: trId, title: "Test Results — 2026-03-24", position: 5,
    is_journal: false, created_at: now, updated_at: now,
  });

  [
    "# MiNotes Test Results & UX Review",
    "Generated by automated testing with agent-browser v0.22.1",
    "## Test Suite Summary",
    "- **Smoke Test**: 6/6 passed (app loads, journal, navigation, search, settings)",
    "- **E2E Suite**: 42/42 passed (all features exist and respond)",
    "- **Slash Commands**: 11/12 passed (headings, lists, quotes, divider)",
    "- **Funnel Tests**: 31/32 passed (complete user journeys)",
    "- **Rust Unit Tests**: 55/55 passed (backend logic)",
    "- **Total: 145 passed, 2 failed**",
    "## Funnel Test Details",
    "### Create Page & Write Content — 5/5 PASS",
    "- [x] Navigate to page",
    "- [x] Blocks visible",
    "- [x] Read block content",
    "- [x] Modify block",
    "- [x] Editor shows update",
    "### Todo List — 4/5 PASS",
    "- [x] Checkbox renders as real taskList node",
    "- [x] Task text visible in accessibility tree",
    "- [x] Multiple task items render",
    "- [ ] Mixed checked/unchecked detection (test pattern issue)",
    "### Headings — 3/3 PASS",
    "- [x] H1 renders as heading element",
    "- [x] H2 renders as heading element",
    "- [x] H1 visible in accessibility tree",
    "### All Other Funnels — PASS",
    "- [x] Bullet list renders correctly",
    "- [x] Blockquote renders correctly",
    "- [x] Code block renders correctly",
    "- [x] Divider renders correctly",
    "- [x] Wiki links are clickable",
    "- [x] Search shows all pages",
    "- [x] Settings has all sections",
    "- [x] Journal date navigation works",
    "- [x] Page navigation works end-to-end",
  ].forEach((content, i) => {
    const bid = genId();
    blocks.set(bid, {
      id: bid, page_id: trId, position: i + 1,
      content, format: "markdown", collapsed: false,
      created_at: now, updated_at: now,
    });
  });

  // UX Design Review page
  const uxId = genId();
  pages.set(uxId, {
    id: uxId, title: "UX Design Review — 2026-03-24", position: 6,
    is_journal: false, created_at: now, updated_at: now,
  });

  [
    "# UX Design Review",
    "Automated screenshot analysis of MiNotes UI via agent-browser",
    "## What Works Well",
    "- [x] Clean dark theme with good contrast (Catppuccin Mocha)",
    "- [x] Sidebar layout is organized and readable",
    "- [x] Settings panel is compact with 2-column keyboard shortcuts",
    "- [x] Wiki links render as clickable blue text",
    "- [x] Bold/inline formatting renders correctly",
    "- [x] Headings are visually distinct and properly sized",
    "- [x] Page header shows title + metadata",
    "## High Priority Issues",
    "TODO Nested blocks dont show visual indentation — data-depth not rendering in mock data",
    "TODO Task states (TODO/DOING/DONE) need colored badges: yellow, blue, green+strikethrough",
    "## Medium Priority Issues",
    "TODO Hide + alias by default — takes space, rarely used",
    "TODO Hide Unlinked References when empty — reduces noise",
    "TODO H1 block redundant with page title header",
    "TODO Format journal date as human-readable (Monday, March 24, 2026)",
    "## Recommended Quick Wins",
    "- [ ] Hide empty Unlinked References (5 min)",
    "- [ ] Hide + alias by default (5 min)",
    "- [ ] Color TODO/DOING/DONE badges (15 min)",
    "- [ ] Format journal date nicely (10 min)",
    "## Bugs Found & Fixed",
    "DONE Enter inside task lists now creates new list item (was creating new block)",
    "DONE Test API methods no longer overwrite each other (mutable singleton)",
    "DONE ProseMirror input — created window.__MINOTES__ test API as workaround",
    "DOING Slash command focus — cursor doesnt land inside task list item after creation",
  ].forEach((content, i) => {
    const bid = genId();
    blocks.set(bid, {
      id: bid, page_id: uxId, position: i + 1,
      content, format: "markdown", collapsed: false,
      created_at: now, updated_at: now,
    });
  });
}

seedData();

// ── Helper functions ──

function getPageBlocks(pageId: string): Block[] {
  return Array.from(blocks.values())
    .filter(b => b.page_id === pageId)
    .sort((a, b) => a.position - b.position);
}

function findPage(titleOrId: string): Page | undefined {
  return pages.get(titleOrId) ??
    Array.from(pages.values()).find(p => p.title === titleOrId);
}

// ── Mock API handlers ──

export const mockHandlers: Record<string, (args: any) => any> = {
  list_pages: ({ limit }: { limit?: number }) => {
    const all = Array.from(pages.values())
      .filter(p => {
        if (trash.has(p.id) || archived.has(p.id)) return false;
        // Hide journals that have no real content (only empty blocks or no blocks)
        if (p.is_journal) {
          const pageBlocks = getPageBlocks(p.id);
          return pageBlocks.some(b => b.content.trim().length > 0);
        }
        return true;
      })
      .sort((a, b) => a.position - b.position);
    return all.slice(0, limit ?? 100);
  },

  get_page_tree: ({ titleOrId }: { titleOrId: string }) => {
    const page = findPage(titleOrId);
    if (!page) throw new Error(`Page not found: ${titleOrId}`);
    return { page, blocks: getPageBlocks(page.id) };
  },

  create_page: ({ title }: { title: string }) => {
    const existing = Array.from(pages.values()).find(p => p.title === title);
    if (existing) throw new Error(`Page '${title}' already exists`);
    const id = genId();
    const page: Page = {
      id, title, position: pages.size + 1,
      is_journal: false, created_at: now, updated_at: now,
    };
    pages.set(id, page);
    return page;
  },

  delete_page: ({ id }: { id: string }) => {
    pages.delete(id);
    for (const [bid, block] of blocks) {
      if (block.page_id === id) blocks.delete(bid);
    }
    return true;
  },

  rename_page: ({ id, newTitle }: { id: string; newTitle: string }) => {
    const page = pages.get(id);
    if (!page) throw new Error("Page not found");
    page.title = newTitle;
    page.updated_at = new Date().toISOString();
    return page;
  },

  create_block: ({ pageId, content, parentId }: { pageId: string; content: string; parentId?: string }) => {
    // If this is for a pending journal, only persist if content is non-empty
    if (content && content.trim().length > 0) {
      for (const [date, pending] of pendingJournals) {
        if (pending.id === pageId) {
          pages.set(pending.id, pending);
          pendingJournals.delete(date);
          break;
        }
      }
    }

    const id = genId();
    const siblings = getPageBlocks(pageId);
    const maxPos = siblings.length > 0 ? Math.max(...siblings.map(b => b.position)) : 0;
    const block: Block = {
      id, page_id: pageId, parent_id: parentId,
      position: maxPos + 1, content: content ?? "",
      format: "markdown", collapsed: false,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    };
    blocks.set(id, block);
    return block;
  },

  update_block: ({ id, content }: { id: string; content: string }) => {
    const block = blocks.get(id);
    if (!block) throw new Error("Block not found");
    block.content = content;
    block.updated_at = new Date().toISOString();

    // If this block belongs to a pending journal and has real content, persist it
    if (content && content.trim().length > 0) {
      for (const [date, pending] of pendingJournals) {
        if (pending.id === block.page_id) {
          pages.set(pending.id, pending);
          pendingJournals.delete(date);
          break;
        }
      }
    }

    return block;
  },

  delete_block: ({ id }: { id: string }) => {
    blocks.delete(id);
    return true;
  },

  move_block: ({ id, newParent, position }: { id: string; newParent: string; position: number }) => {
    const block = blocks.get(id);
    if (!block) throw new Error("Block not found");
    block.parent_id = newParent;
    block.position = position;
    return block;
  },

  reparent_block: ({ id, parentId }: { id: string; parentId?: string }) => {
    const block = blocks.get(id);
    if (!block) throw new Error("Block not found");
    block.parent_id = parentId;
    return block;
  },

  reorder_block: ({ id, parentId, position }: { id: string; parentId?: string; position: number }) => {
    const block = blocks.get(id);
    if (!block) throw new Error("Block not found");
    block.parent_id = parentId;
    block.position = position;
    return block;
  },

  search_blocks: ({ query, limit }: { query: string; limit?: number }) => {
    const q = query.toLowerCase();
    return Array.from(blocks.values())
      .filter(b => b.content.toLowerCase().includes(q))
      .slice(0, limit ?? 20);
  },

  get_backlinks: ({ pageId }: { pageId: string }) => {
    return [] as Link[];
  },

  get_unlinked_references: ({ pageId }: { pageId: string }) => {
    return [] as Block[];
  },

  get_graph_stats: () => {
    return {
      pages: pages.size,
      blocks: blocks.size,
      links: 0,
      properties: 0,
      events: 0,
      orphan_pages: 0,
      journal_pages: Array.from(pages.values()).filter(p => p.is_journal).length,
    } as GraphStats;
  },

  get_graph_data: () => {
    return {
      nodes: Array.from(pages.values()).map(p => ({
        id: p.id, title: p.title,
        block_count: getPageBlocks(p.id).length,
        link_count: 0,
      })),
      edges: [],
    } as GraphData;
  },

  run_query: ({ sql }: { sql: string }) => {
    return { columns: ["info"], rows: [{ info: "Mock backend — SQL not supported" }] } as QueryResult;
  },

  get_journal: ({ date }: { date?: string }) => {
    const d = date ?? today;
    const title = `Journal/${d}`;
    let page = Array.from(pages.values()).find(p => p.title === title);
    if (!page) {
      const id = genId();
      page = {
        id, title, position: pages.size + 1,
        is_journal: true, journal_date: d,
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
      };
      pages.set(id, page);
    }
    return { page, blocks: getPageBlocks(page.id) };
  },

  get_folder_tree: () => {
    const rootPages = Array.from(pages.values())
      .filter(p => !p.folder_id && !p.is_journal && !trash.has(p.id) && !archived.has(p.id))
      .sort((a, b) => a.position - b.position);
    // Build folder tree
    const buildTree = (parentId?: string): any[] => {
      return Array.from(folders.values())
        .filter(f => (f.parent_id ?? undefined) === parentId && !trashedFolders.has(f.id) && !archivedFolders.has(f.id))
        .sort((a, b) => a.position - b.position)
        .map(f => ({
          ...f,
          children: buildTree(f.id),
          pages: Array.from(pages.values())
            .filter(p => p.folder_id === f.id && !trash.has(p.id) && !archived.has(p.id))
            .sort((a, b) => a.position - b.position),
        }));
    };
    return { folders: buildTree(undefined), root_pages: rootPages } as FolderTreeRoot;
  },

  create_folder: ({ name, parentId }: { name: string; parentId?: string }) => {
    const id = genId();
    const folder: MockFolder = { id, name, parent_id: parentId, position: folders.size, collapsed: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() };
    folders.set(id, folder);
    return folder;
  },

  move_page_to_folder: ({ pageId, folderId }: { pageId: string; folderId?: string }) => {
    const page = pages.get(pageId);
    if (!page) throw new Error("Page not found");
    page.folder_id = folderId;
    return page;
  },

  reorder_page: ({ id, newPosition }: { id: string; newPosition: number }) => {
    const page = pages.get(id);
    if (!page) throw new Error("Page not found");
    page.position = newPosition;
    return page;
  },

  delete_folder: ({ id }: { id: string }) => {
    // Move pages to root
    for (const p of pages.values()) {
      if (p.folder_id === id) p.folder_id = undefined;
    }
    folders.delete(id);
    return true;
  },
  rename_folder: ({ id, newName }: { id: string; newName: string }) => {
    const f = folders.get(id);
    if (f) { f.name = newName; f.updated_at = new Date().toISOString(); return f; }
    return { id, name: newName, position: 0, collapsed: false, created_at: now, updated_at: now };
  },
  update_folder_appearance: ({ id, icon, color }: { id: string; icon?: string; color?: string }) => {
    const f = folders.get(id);
    if (f) {
      if (icon !== undefined && icon !== null) f.icon = icon;
      if (color !== undefined && color !== null) f.color = color;
      f.updated_at = new Date().toISOString();
      return f;
    }
    return { id, name: "", icon, color, position: 0, collapsed: false, created_at: now, updated_at: now };
  },

  set_property: ({ entityId, entityType, key, value, valueType }: any) => {
    const prop: Property = {
      id: genId(), entity_id: entityId, entity_type: entityType,
      key, value, value_type: valueType ?? "text",
      created_at: now, updated_at: now,
    };
    const existing = properties.get(entityId) ?? [];
    const idx = existing.findIndex(p => p.key === key);
    if (idx >= 0) existing[idx] = prop; else existing.push(prop);
    properties.set(entityId, existing);
    return prop;
  },

  get_properties: ({ entityId }: { entityId: string }) => {
    return properties.get(entityId) ?? [];
  },

  get_inherited_properties: ({ blockId }: { blockId: string }) => {
    return properties.get(blockId) ?? [];
  },

  delete_property: ({ entityId, key }: { entityId: string; key: string }) => {
    const existing = properties.get(entityId) ?? [];
    properties.set(entityId, existing.filter(p => p.key !== key));
    return true;
  },

  // Stubs for features that don't need full mock
  add_favorite: ({ pageId }: { pageId: string }) => {
    if (!favorites.has(pageId)) {
      const maxPos = favorites.size > 0 ? Math.max(...favorites.values()) : 0;
      favorites.set(pageId, maxPos + 1);
    }
  },
  remove_favorite: ({ pageId }: { pageId: string }) => {
    favorites.delete(pageId);
    return true;
  },
  list_favorites: () => {
    return Array.from(favorites.entries())
      .sort((a, b) => a[1] - b[1])
      .map(([id, pos]) => {
        const page = pages.get(id);
        if (!page) return null;
        return { ...page, position: pos }; // Use favorites position, not page position
      })
      .filter(Boolean) as Page[];
  },
  add_alias: () => {},
  remove_alias: () => true,
  get_aliases: () => [],
  create_template: () => ({ id: genId(), name: "", content: "", created_at: now, updated_at: now }),
  list_templates: () => [],
  apply_template: () => [],
  delete_template: () => true,
  export_opml: () => "<opml></opml>",
  export_json: () => ({ pages: [] }),
  publish_site: () => [],
  list_plugins: () => [],
  register_plugin: () => ({ id: genId(), name: "", version: "0.1.0", enabled: true, created_at: now, updated_at: now }),
  enable_plugin: () => ({ id: "", name: "", version: "", enabled: true, created_at: now, updated_at: now }),
  disable_plugin: () => ({ id: "", name: "", version: "", enabled: false, created_at: now, updated_at: now }),
  uninstall_plugin: () => true,
  create_card: () => ({ id: genId(), block_id: "", card_type: "basic", due: now, stability: 0, difficulty: 0, reps: 0, lapses: 0, state: "new", created_at: now, updated_at: now }),
  get_due_cards: () => [],
  review_card: () => ({ id: "", block_id: "", card_type: "basic", due: now, stability: 0, difficulty: 0, reps: 0, lapses: 0, state: "review", created_at: now, updated_at: now }),
  get_srs_stats: () => ({ due_count: 0, reviewed_today: 0, total_cards: 0 }),
  delete_card: () => true,
  list_graphs: () => [],
  switch_graph: () => true,
  create_graph_cmd: () => ({ name: "default", path: "", size_bytes: 0, modified_at: now }),
  delete_graph_cmd: () => true,
  get_current_graph: () => "default",
  clip_content: () => ({ id: genId(), title: "", position: 0, is_journal: false, created_at: now, updated_at: now }),
  create_highlight: () => ({ id: genId(), pdf_path: "", page_num: 0, x: 0, y: 0, width: 0, height: 0, color: "yellow", created_at: now, updated_at: now }),
  get_highlights: () => [],
  update_highlight_note: () => ({ id: "", pdf_path: "", page_num: 0, x: 0, y: 0, width: 0, height: 0, color: "yellow", created_at: now, updated_at: now }),
  delete_highlight: () => true,
  search_highlights: () => [],
  undo: () => null,
  get_sync_status: () => ({ total_pages: 0, synced_pages: 0, pending_changes: 0 }),
  sync_page: () => [],
  get_version_history: () => [],
  restore_version: () => {},
  plugin_storage_get: () => null,
  plugin_storage_set: () => {},
  add_css_snippet: () => ({ id: genId(), name: "", css: "", enabled: true, source: "custom", created_at: now }),
  list_css_snippets: () => [],
  toggle_css_snippet: () => ({ id: "", name: "", css: "", enabled: true, source: "custom", created_at: now }),
  delete_css_snippet: () => true,
  get_enabled_css_snippets: () => [],
  save_png_to_downloads: ({ filename }: { filename: string }) => `Downloads/${filename}`,

  // Feature 8: Link Preview — mock OG metadata
  fetch_og_metadata: ({ url }: { url: string }) => ({
    title: new URL(url).hostname + " — Page Title",
    description: "A brief description of the linked page content.",
    image: "",
  }),

  // Feature 9: Block Transclusion — get single block by ID
  get_block: ({ id }: { id: string }) => {
    return blocks.get(id) ?? null;
  },

  reorder_favorite: ({ pageId, newPosition }: { pageId: string; newPosition: number }) => {
    if (favorites.has(pageId)) {
      favorites.set(pageId, newPosition);
    }
  },

  // Archive
  archive_page: ({ id }: { id: string }) => { archived.add(id); favorites.delete(id); },
  unarchive_page: ({ id }: { id: string }) => { archived.delete(id); },
  archive_folder: ({ id }: { id: string }) => {
    let count = 0;
    for (const p of pages.values()) {
      if (p.folder_id === id && !archived.has(p.id)) { archived.add(p.id); favorites.delete(p.id); count++; }
    }
    archivedFolders.add(id);
    return count;
  },
  unarchive_folder: ({ id }: { id: string }) => {
    archivedFolders.delete(id);
    for (const p of pages.values()) {
      if (p.folder_id === id) archived.delete(p.id);
    }
  },
  list_archived: () => {
    const items: Page[] = [];
    // Pages archived directly
    for (const pid of archived) {
      const p = pages.get(pid);
      if (p) items.push(p);
    }
    // Pages in archived folders (not already in archived set)
    for (const fid of archivedFolders) {
      for (const p of pages.values()) {
        if (p.folder_id === fid && !archived.has(p.id)) items.push(p);
      }
    }
    return items;
  },
  archived_count: () => archived.size + Array.from(pages.values()).filter(p => p.folder_id && archivedFolders.has(p.folder_id) && !archived.has(p.id)).length,

  // Trash
  trash_page: ({ id }: { id: string }) => {
    trash.add(id);
    favorites.delete(id);
  },
  trash_folder: ({ id }: { id: string }) => {
    let count = 0;
    for (const p of pages.values()) {
      if (p.folder_id === id && !trash.has(p.id)) {
        trash.add(p.id);
        favorites.delete(p.id);
        count++;
      }
    }
    trashedFolders.add(id);
    return count;
  },
  restore_from_trash: ({ id, itemType }: { id: string; itemType: string }) => {
    if (itemType === "folder") {
      trashedFolders.delete(id);
      for (const p of pages.values()) {
        if (p.folder_id === id) trash.delete(p.id);
      }
    } else {
      trash.delete(id);
    }
  },
  permanently_delete: ({ id, itemType }: { id: string; itemType: string }) => {
    if (itemType === "folder") {
      trashedFolders.delete(id);
      for (const [pid, p] of pages) {
        if (p.folder_id === id) { trash.delete(pid); pages.delete(pid); }
      }
      folders.delete(id);
    } else {
      trash.delete(id);
      pages.delete(id);
      for (const [bid, block] of blocks) {
        if (block.page_id === id) blocks.delete(bid);
      }
    }
  },
  list_trash: () => {
    const items: Array<{ id: string; title: string; item_type: string; page_count: number; deleted_at: string }> = [];
    // Trashed folders
    for (const fid of trashedFolders) {
      const f = folders.get(fid);
      if (f) {
        const pageCount = Array.from(pages.values()).filter(p => p.folder_id === fid).length;
        items.push({ id: fid, title: f.name, item_type: "folder", page_count: pageCount, deleted_at: new Date().toISOString() });
      }
    }
    // Trashed pages (not in a trashed folder)
    for (const pid of trash) {
      const p = pages.get(pid);
      if (p && (!p.folder_id || !trashedFolders.has(p.folder_id))) {
        items.push({ id: p.id, title: p.title, item_type: "page", page_count: 0, deleted_at: new Date().toISOString() });
      }
    }
    return items;
  },
  empty_trash: () => {
    let count = trashedFolders.size;
    for (const fid of trashedFolders) {
      for (const [pid, p] of pages) {
        if (p.folder_id === fid) { pages.delete(pid); trash.delete(pid); }
      }
      folders.delete(fid);
    }
    trashedFolders.clear();
    for (const pid of trash) {
      pages.delete(pid);
      count++;
    }
    trash.clear();
    return count;
  },

  // Git Sync
  git_available: () => true,
  git_sync_enable: () => ({
    enabled: true,
    remote_url: null,
    branch: "main",
    last_sync: new Date().toISOString(),
  }),
  git_sync_disable: () => {},
  git_sync: () => ({
    success: true,
    pages_exported: 0,
    pages_imported: 0,
    conflicts_resolved: 0,
    error: null,
  }),
  git_sync_status: () => ({
    enabled: false,
    remote_url: null,
    branch: null,
    last_sync: null,
  }),
};
